CREATE TABLE FoodLogs (
    FoodLogId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    FoodId INT NOT NULL,
    UserId INT NULL,
    Date DATE NOT NULL,
    CreatedAtUtc TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CreatedByUserId INT,
    LastUpdatedAtUtc TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    LastUpdatedByUserId INT
);

CREATE TABLE Foods (
    FoodId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR NOT NULL,
    Calories DECIMAL NULL,
    Protein DECIMAL NULL,
    Fat DECIMAL NULL,
    Unit VARCHAR NOT NULL,
    Amount INT NOT NULL,
    CreatedAtUtc TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CreatedByUserId INT,
    LastUpdatedAtUtc TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    LastUpdatedByUserId INT
);
