CREATE TABLE ExerciseLogs (
    ExerciseLogId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ExerciseLogFirebaseId VARCHAR NOT NULL,
    Username VARCHAR NULL,
    UserId INT NULL,
    UserFirebaseUuid VARCHAR NULL,
    ExerciseId INT NULL,
    ExerciseFirebaseId VARCHAR NOT NULL,
    Date DATE NOT NULL
);

CREATE TABLE Series (
    SerieId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ExerciseLogId INT NOT NULL,
    ExerciseLogFirebaseId VARCHAR NOT NULL,
    Reps INT NOT NULL,
    WeightInKg DECIMAL NOT NULL
);

CREATE TABLE Users (
    UserId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    UserFirebaseUuid VARCHAR NOT NULL,
    Email VARCHAR NOT NULL,
    Name VARCHAR NOT NULL
);

CREATE TABLE Exercises (
    ExerciseId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ExerciseFirebaseId VARCHAR NOT NULL,
    Name VARCHAR NOT NULL,
    MuscleGroup VARCHAR NOT NULL,
    Type VARCHAR NOT NULL
);
