INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLd93FrbBR1i6cQP', 'pecho plano', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdBdvEJr1CB9LzJ', 'pecho inclinado', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdBdvEJr1CB9LzK', 'pec fly', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdCVqZT4bcLrfng', 'chest press', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdCVqZT4bcLrfnh', 'overhead press', 'shoulders', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdCVqZT4bcLrfni', 'shoulder press db', 'shoulders', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdDSXpEXFVDM-GH', 'lateral raises polea', 'shoulders', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdDSXpEXFVDM-GI', 'lateral raises db', 'shoulders', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdDSXpEXFVDM-GJ', 'press militar banco db', 'shoulders', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdDSXpEXFVDM-GK', 'tricep polea soga', 'arms', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdDSXpEXFVDM-GL', 'tricep polea barra', 'arms', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdDSXpEXFVDM-GM', 'skullcrusher', 'arms', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxe', 'pecho inclinado smith', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxf', 'cruce polea', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxg', 'pecho inclinado db', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxh', 'apertura banco db', 'chest', 'push');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxi', 'pulldown over', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxj', 'pulldown under', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxk', 'pulldown v', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxl', 'remo cerrucho', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxm', 'remo olimpico', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxn', 'remo caballo', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxo', 'remo landmine', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdESukp-cc7pJxp', 'remo maquina', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRM', 'shrugs', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRN', 'shrugs db', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRO', 'pull-ups', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRP', 'chin-ups', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRQ', 'bicep curl', 'arms', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRR', 'bicep martillo', 'arms', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRS', 'bicep preacher db', 'arms', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRT', 'espinales', 'back', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRU', 'forearm barra', 'arms', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRV', 'sentadilla', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRW', 'sentadilla bulgara', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRX', 'sillon cuadricep', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRY', 'sillon cuadricep 1 pierna', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRZ', 'femorales', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVR_', 'gemelos', 'calves', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRa', 'patada', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRb', 'peso muerto', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdFnTZCSwL5DVRc', 'hip thrust', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hl', 'hip thrust polea', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hm', 'sentadilla smith', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hn', 'abductores', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Ho', 'leg press', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hp', 'zancada smith', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hq', 'rumanas db', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hr', 'zancada', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NmNQLdGmAJ0LekxE2Hs', 'sillon gemelos', 'calves', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-Nr81Nkx3i4hbW4cKWWA', 'bicep polea barra', 'arms', 'pull');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NrghS8w0MHLXcdoye4B', 'gemelos smith 1 pierna', 'calves', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-NsQ0S3sYq8zcQhXprsV', 'peso muerto rumano', 'legs', 'legs');
INSERT INTO Exercises (ExerciseFirebaseId, Name, MuscleGroup, Type) VALUES ('-Ntri4i67XAXdFMdZJWp', 'maquina row rear delt', 'back', 'pull');
