ALTER TABLE FoodLogs
  ALTER COLUMN FoodId DROP NOT NULL,
  ALTER COLUMN Amount DROP NOT NULL,
  ADD COLUMN QuickAdd BOOLEAN NULL,
  ADD COLUMN Description VARCHAR(255) NULL,
  ADD COLUMN Calories DECIMAL NULL,
  ADD COLUMN Protein DECIMAL NULL,
  ADD COLUMN Fat DECIMAL NULL;