# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - robertly

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: robertly
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          # include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./robertly-net-api/robertly-net-api.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./robertly-net-api/robertly-net-api.sln -c Release -o '$***REMOVED******REMOVED*** env.$AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: $***REMOVED******REMOVED*** env.AZURE_WEBAPP_NAME ***REMOVED******REMOVED***
          package: $***REMOVED******REMOVED*** env.AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***
          publish-profile: $***REMOVED******REMOVED*** secrets.AZURE_PUBLISH_PROFILE ***REMOVED******REMOVED***

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: .net-app
      #     path: $***REMOVED******REMOVED***env.DOTNET_ROOT***REMOVED******REMOVED***/myapp

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: $***REMOVED******REMOVED*** steps.deploy-to-webapp.outputs.webapp-url ***REMOVED******REMOVED***

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: .net-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: $***REMOVED******REMOVED*** AZURE_WEBAPP_NAME ***REMOVED******REMOVED***
  #         package: $***REMOVED******REMOVED*** AZURE_WEBAPP_PACKAGE_PATH ***REMOVED******REMOVED***
  #         publish-profile: $***REMOVED******REMOVED*** secrets.AZURE_PUBLISH_PROFILE ***REMOVED******REMOVED***

  # deploy:
  #   runs-on: windows-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: $***REMOVED******REMOVED*** steps.deploy-to-webapp.outputs.webapp-url ***REMOVED******REMOVED***

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: .net-app

  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: 'robertly'
  #         slot-name: 'Production'
  #         package: .
  #         publish-profile: $***REMOVED******REMOVED*** secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2F5821C575B949918E83500E869CD964 ***REMOVED******REMOVED***
