name: Build and deploy robertly-ui

on:
  push:
    branches:
      - main
    paths:
      - robertly-ui/**
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        cd ./robertly-ui
        npm ci
        npm run build
        npm run deploy
